telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "mybot.py", line 43, in get_constellation
    if planet == 'Mars':
UnboundLocalError: local variable 'planet' referenced before assignment
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "mybot.py", line 45, in get_constellation
    planet = ephem.Mars(datetime.date.today())
AttributeError: 'method_descriptor' object has no attribute 'today'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "mybot.py", line 64, in get_constellation
    constel = ephem.constellation(planet)
UnboundLocalError: local variable 'planet' referenced before assignment
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
